# Generated by Django 4.2.2 on 2023-06-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0002_remove_detallepedido_pedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombreProducto', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('precio', models.CharField(max_length=30)),
                ('stock', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('contraseña', models.CharField(max_length=30)),
            ],
        ),
    ]
